main:
  allow-circular-references: true

server:
  servlet:
    context-path: /events

spring:
  datasource:
    url: jdbc:h2:./events
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console